#
#  $$$$$$$$\           $$\
#  \__$$  __|          $$ |
#     $$ |    $$$$$$\  $$ |  $$\  $$$$$$\  $$$$$$$\   $$$$$$$\
#     $$ |   $$  __$$\ $$ | $$  |$$  __$$\ $$  __$$\ $$  _____|
#     $$ |   $$ /  $$ |$$$$$$  / $$$$$$$$ |$$ |  $$ |\$$$$$$\
#     $$ |   $$ |  $$ |$$  _$$<  $$   ____|$$ |  $$ | \____$$\
#     $$ |   \$$$$$$  |$$ | \$$\ \$$$$$$$\ $$ |  $$ |$$$$$$$  |
#     \__|    \______/ \__|  \__| \_______|\__|  \__|\_______/
#
# Tokens 1.0
# By Optimal Services
# Discord: optimal-services.org/discord| ImKlat#0195 |
# Twitter: @OptimalConfigs
#

MySQL:
  HOSTNAME: 'localhost'
  PORT: 3306
  DATABASE: 'tokens'
  USERNAME: 'root'
  PASSWORD: ''